export const ActionsType = {
  SET_PRODUCT: "SET_PRODUCT",
  SHOW_MORE_PRODUCT: "SHOW_MORE_PRODUCT",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  INC: "INC",
  DEC: "DEC",
};
